dataset_dir:
dataset_workers: 4
split:
  train: 0.8
  validation: 0.1
  test: 0.1
batch_size: 2
learning_rate: 0.2
epochs: 1
save_best_model_only: True
start_checkpoint:
test_checkpoint:
prediction_threshold: 0.1
mixed_precision_enabled: True
gradient_acc_steps: 1